# Generated by Django 5.0.6 on 2025-04-16 02:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('calories_per_100g', models.FloatField()),
                ('protein', models.FloatField(default=0)),
                ('carb', models.FloatField(default=0)),
                ('fat', models.FloatField(default=0)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MealAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(max_length=500)),
                ('total_calories', models.FloatField(default=0)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('food_items', models.ManyToManyField(related_name='meals', to='analysis.fooditem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-analyzed_at'],
            },
        ),
    ]
