# Generated by Django 5.0.6 on 2025-05-08 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealanalysis',
            name='image',
            field=models.ImageField(upload_to='meals'),
        ),
    ]
